import exceptions

raise Exception('a exception')
